Repository ASUS-AICS/LibMultiLabel, pull requests merged in 2021-11, with the labels that each got.

#103 Remove network config from argparse.
  main.py
Labels: bug

#101 [Doc] Move README to CLI
  README.md
  docs/api/api.rst
  docs/cli.rst
  docs/cli/cli.rst
  docs/cli/data_format.rst
  docs/cli/linear.rst
  docs/cli/nn.rst
  docs/cli/options.rst
  docs/index.rst
  docs/installation.rst
  docs/tutorial/nn_api_tutorial.rst
  torch_trainer.py
Labels: documentation

#106 Update load_checkpoint -> checkpoint_path
  docs/cli/nn.rst
Labels: documentation

#113 Update sidebar structure
  docs/api/api.rst
  docs/api/nn.rst
  docs/index.rst
  docs/installation.rst
  docs/tutorial/nn_api_tutorial.rst
Labels: documentation

#112 Update `search_params.py`
  example_config/MIMIC-50/caml_tune.yml
  example_config/rcv1/cnn_tune.yml
  requirements_parameter_search.txt
  search_params.py
  torch_trainer.py
Labels: enhancement

#116 Add link to the datasets
  docs/cli/cli.rst
  docs/cli/data_format.rst
Labels: documentation

#124 Update example of NN API
  docs/api/api.rst
  docs/examples/nn_quickstart.py
Labels: documentation

#119 Reorganizing documentation
  docs/api/linear.rst
  docs/cli/cli.rst
  docs/cli/linear.rst
  docs/cli/nn.rst
  docs/cli/options.rst
  docs/cli/ov_data_format.rst
  docs/guides/linear_guides.rst
  docs/guides/nn_guides.rst
  docs/index.rst
  example_config/rcv1/l2svm.yml
Labels: documentation

#127 Update example for new NN API
  docs/examples/nn_quickstart.py
Labels: documentation

#122 Updated API Getting Started
  docs/api/api.rst
  docs/api/linear.rst
  docs/api/linear_tutorial.rst
  docs/api/nn.rst
  docs/api/nn_tutorial.rst
  docs/examples/linear_quickstart.py
  docs/index.rst
  libmultilabel/linear/linear.py
Labels: documentation
