Repository ASUS-AICS/LibMultiLabel, pull requests merged in 2023-09, with the labels that each got.

#331 Update version to 0.3.3
  setup.cfg
Labels: release

#328 Replace existing thresholding with micromacro
  libmultilabel/linear/linear.py
Labels: model/linear

#326 Add linear recall
  docs/api/linear.rst
  libmultilabel/linear/metrics.py
Labels: feature, model/linear

#329 Only log relevant config
  libmultilabel/common_utils.py
  search_params.py
  torch_trainer.py
Labels: enhancement, model/linear

#334 Add retrain tutorial
  docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
Labels: documentation
