Repository ASUS-AICS/LibMultiLabel, pull requests merged in 2023-07, with the labels that each got.

#318 [TorchText] Bug: Hotfix Glove URLs
  libmultilabel/nn/data_utils.py
Labels: bug

#317 Add lr scheduler for LAAT (ReduceOnPlateau)
  libmultilabel/nn/model.py
  libmultilabel/nn/nn_utils.py
  main.py
  search_params.py
  torch_trainer.py
Labels: feature

#305 Load checkpoint with new model configuration.
  libmultilabel/nn/model.py
  torch_trainer.py
Labels: bug, model/nn

#320 add lr_scheduler and scheduler_config
  example_config/EUR-Lex-57k/bert_lwan_tune.yml
  example_config/EUR-Lex-57k/bigru_lwan_tune.yml
  example_config/EUR-Lex-57k/cnn_lwan_tune.yml
  example_config/EUR-Lex-57k/kim_cnn_tune.yml
  example_config/EUR-Lex/bigru_lwan_tune.yml
  example_config/EUR-Lex/cnn_lwan_tune.yml
  example_config/EUR-Lex/kim_cnn_tune.yml
  example_config/MIMIC-50/bigru_lwan_tune.yml
  example_config/MIMIC-50/caml_tune.yml
  example_config/MIMIC/bigru_lwan_tune.yml
  example_config/MIMIC/cnn_lwan_tune.yml
  example_config/MIMIC/kim_cnn_tune.yml
  example_config/Wiki10-31K/bigru_lwan_tune.yml
  example_config/Wiki10-31K/cnn_lwan_tune.yml
  example_config/Wiki10-31K/kim_cnn_tune.yml
  example_config/rcv1/cnn_tune.yml
Labels: bug, parameter-search

#322 fix bugs of search_params;
  search_params.py
Labels: bug, parameter-search

#315 Homogenizing Dropout
  docs/examples/plot_KimCNN_quickstart.py
  docs/examples/plot_bert_quickstart.py
  example_config/EUR-Lex-57k/bert.yml
  example_config/EUR-Lex-57k/bert_lwan.yml
  example_config/EUR-Lex-57k/bert_lwan_tune.yml
  example_config/EUR-Lex-57k/bigru_lwan.yml
  example_config/EUR-Lex-57k/bigru_lwan_tune.yml
  example_config/EUR-Lex-57k/cnn_lwan.yml
  example_config/EUR-Lex-57k/cnn_lwan_tune.yml
  example_config/EUR-Lex-57k/kim_cnn.yml
  example_config/EUR-Lex-57k/kim_cnn_tune.yml
  example_config/EUR-Lex/bigru_lwan.yml
  example_config/EUR-Lex/bigru_lwan_tune.yml
  example_config/EUR-Lex/cnn_lwan.yml
  example_config/EUR-Lex/cnn_lwan_tune.yml
  example_config/EUR-Lex/kim_cnn.yml
  example_config/EUR-Lex/kim_cnn_tune.yml
  example_config/EUR-Lex/xml_cnn.yml
  example_config/MIMIC-50/bert_lwan.yml
  example_config/MIMIC-50/bigru_lwan.yml
  example_config/MIMIC-50/bigru_lwan_tune.yml
  example_config/MIMIC-50/caml.yml
  example_config/MIMIC-50/caml_tune.yml
  example_config/MIMIC-50/cnn.yml
  example_config/MIMIC/bigru_lwan.yml
  example_config/MIMIC/bigru_lwan_tune.yml
  example_config/MIMIC/cnn_lwan.yml
  example_config/MIMIC/cnn_lwan_tune.yml
  example_config/MIMIC/kim_cnn.yml
  example_config/MIMIC/kim_cnn_tune.yml
  example_config/Wiki10-31K/bigru_lwan.yml
  example_config/Wiki10-31K/bigru_lwan_tune.yml
  example_config/Wiki10-31K/cnn_lwan.yml
  example_config/Wiki10-31K/cnn_lwan_tune.yml
  example_config/Wiki10-31K/kim_cnn.yml
  example_config/Wiki10-31K/kim_cnn_tune.yml
  example_config/rcv1/cnn_tune.yml
  example_config/rcv1/kim_cnn.yml
  example_config/rcv1/xml_cnn.yml
  libmultilabel/nn/networks/bert.py
  libmultilabel/nn/networks/bert_attention.py
  libmultilabel/nn/networks/caml.py
  libmultilabel/nn/networks/kim_cnn.py
  libmultilabel/nn/networks/labelwise_attention_networks.py
  libmultilabel/nn/networks/modules.py
  libmultilabel/nn/networks/xml_cnn.py
Labels: feature, model/nn
