Repository ASUS-AICS/LibMultiLabel, pull requests merged in 2024-04, with the labels that each got.

#365 Increase the Capability of Autotest & Add One More Feature to Fake Text
  tests/basic.sh
Labels: enhancement

#346 Refactored AttentionXML
  example_config/AmazonCat-13K/attentionxml.yml
  example_config/EUR-Lex/attentionxml.yml
  example_config/Wiki10-31K/attentionxml.yml
  libmultilabel/nn/attentionxml.py
  libmultilabel/nn/networks/__init__.py
  libmultilabel/nn/networks/labelwise_attention_networks.py
  libmultilabel/nn/networks/modules.py
  main.py
  torch_trainer.py
Labels: model/nn

#368 Add Tutorial for AttentionXML
  docs/linear.rst
  docs/neural_networks.rst
  docs/tutorial.rst
  docs/tutorials/AttentionXML.rst
  docs/tutorials/images/AttentionXML_training.png
Labels: documentation

#367 Added CLI beam width functionality
  docs/api/linear.rst
  libmultilabel/linear/linear.py
  libmultilabel/linear/tree.py
  linear_trainer.py
Labels: model/linear
