Repository ASUS-AICS/LibMultiLabel, pull requests merged in 2024-01, with the labels that each got.

#345 Release implementation document.
  docs/index.rst
Labels: documentation

#349 Removed redundant line
  setup.cfg
Labels: enhancement

#351 Fixed recall for no label instances
  libmultilabel/linear/metrics.py
  setup.cfg
Labels: bug

#350 A Lighter Timer
  libmultilabel/common_utils.py
  main.py
  run_and_store_results.py
  search_params.py
Labels: enhancement

#356 Fix top_k in metrics.py
  libmultilabel/nn/metrics.py
  setup.cfg
Labels: bug, release
