Repository ASUS-AICS/LibMultiLabel, pull requests merged in 2024-08, with the labels that each got.

#386 Fix Autotest: Set Pytorch <=2.3 to resolve torchtext dependency issue
  requirements_nn.txt
  setup.cfg
Labels: release, version

#385 estimate and print tree model size
  libmultilabel/linear/tree.py
  requirements.txt
Labels: model/linear

#387 fix some typos and consistency
  libmultilabel/linear/linear.py
  libmultilabel/linear/tree.py
Labels: documentation
